@startuml
!theme plain
left to right direction
skinparam packageStyle rectangle

rectangle "Anwendungsfälle" {
    actor "Gast" as guest
    actor "Mitarbeiter" as staff
    rectangle "Anwendung" {
        usecase "Betreten der Einrichtung" as spawn
        usecase "Allgemeiner Informationsbedarf" as info
        usecase "Interesse an Live-Streams" as live_like
        usecase "Interesse an der Uhrzeit" as time
        usecase "Zugriff auf Veranstaltungs- & Termininformationen" as event_customer
        usecase "Verwaltung von Kalendereinträgen" as event_employee
        usecase "Bereitstellung von Video-Stream-Quellen" as live_some
        usecase "Bereitstellung von Laufschrift Text" as marquee
        usecase "Bereitstellung von Hintergrundbildern" as bg
        usecase "Begrüßen von Kunden und Besuchen" as greet
    }

    guest -- spawn
    guest -- info
    guest -- live_like
    guest -- time
    guest -- event_customer

    bg -- staff
    marquee -- staff
    live_some -- staff
    event_employee -- staff
    greet -- staff
}
@enduml
